import type { ProductCard } from "./products.types";

export const mockProductCards: ProductCard[] = [
  {
    id: 101,
    title: "Apple MacBook Pro 14",
    description: "M3 Pro, 18GB RAM, 512GB SSD",
    imageUrl: "https://via.placeholder.com/300x300",
    price: 2199,
    oldPrice: 2399,
    rating: 4.9,
    availability: "In stock",
    productUrl: "/products/101",
  },
  {
    id: 102,
    title: "Apple MacBook Air 13",
    description: "M2, 8GB RAM, 256GB SSD",
    imageUrl: "https://via.placeholder.com/300x300",
    price: 1199,
    rating: 4.7,
    availability: "In stock",
    productUrl: "/products/102",
  },
  {
    id: 103,
    title: "Dell XPS 13",
    description: "Intel Core i7, 16GB RAM, 512GB SSD",
    imageUrl: "https://via.placeholder.com/300x300",
    price: 1499,
    oldPrice: 1699,
    rating: 4.6,
    availability: "Limited",
    productUrl: "/products/103",
  },
  {
    id: 104,
    title: "Dell XPS 15",
    description: "Intel Core i9, 32GB RAM, 1TB SSD",
    imageUrl: "https://via.placeholder.com/300x300",
    price: 2299,
    rating: 4.8,
    availability: "In stock",
    productUrl: "/products/104",
  },
  {
    id: 105,
    title: "HP Spectre x360",
    description: "Intel Core i7, 16GB RAM, 1TB SSD",
    imageUrl: "https://via.placeholder.com/300x300",
    price: 1599,
    rating: 4.5,
    availability: "In stock",
    productUrl: "/products/105",
  },
  {
    id: 106,
    title: "Lenovo ThinkPad X1 Carbon",
    description: "Intel Core i7, 16GB RAM, 512GB SSD",
    imageUrl: "https://via.placeholder.com/300x300",
    price: 1799,
    rating: 4.7,
    availability: "Limited",
    productUrl: "/products/106",
  },
  {
    id: 107,
    title: "Lenovo Legion 5 Pro",
    description: "Ryzen 7, 32GB RAM, 1TB SSD, RTX 4070",
    imageUrl: "https://via.placeholder.com/300x300",
    price: 1899,
    oldPrice: 2099,
    rating: 4.6,
    availability: "In stock",
    productUrl: "/products/107",
  },
  {
    id: 108,
    title: "ASUS ROG Zephyrus G14",
    description: "Ryzen 9, 32GB RAM, 1TB SSD, RTX 4060",
    imageUrl: "https://via.placeholder.com/300x300",
    price: 1999,
    rating: 4.8,
    availability: "In stock",
    productUrl: "/products/108",
  },
  {
    id: 109,
    title: "ASUS ZenBook 14",
    description: "Intel Core i5, 16GB RAM, 512GB SSD",
    imageUrl: "https://via.placeholder.com/300x300",
    price: 999,
    rating: 4.4,
    availability: "In stock",
    productUrl: "/products/109",
  },
  {
    id: 110,
    title: "Acer Swift 3",
    description: "Ryzen 5, 16GB RAM, 512GB SSD",
    imageUrl: "https://via.placeholder.com/300x300",
    price: 849,
    rating: 4.3,
    availability: "Limited",
    productUrl: "/products/110",
  },
];
